#!/usr/bin/env python3
import os
import sys
import json
import subprocess

def find_config(filename):
    curr_dir = os.getcwd()
    while True:
        path = os.path.join(curr_dir, '.agents', filename)
        if os.path.exists(path):
            return path
        parent = os.path.dirname(curr_dir)
        if parent == curr_dir:
            break
        curr_dir = parent
    return None

def main():
    print("====================================================")
    print("🔑 Drunken AGY Inn Environment Setup & Biometric Auth")
    print("====================================================")
    print("[*] บอสครับ ผมจะทำการยืนยันตัวตนด้วย Biometric ผ่าน 1Password CLI")
    print("[*] เพื่อปลดล็อคและดึง credential ที่จำเป็นมาสร้างไฟล์ .env")
    print("----------------------------------------------------")
    
    # Load config template details (defaults to empty/generic)
    jira_email = ""
    jira_url = ""
    project_key = ""
    discord_channel_id = ""
    jira_token = None
    discord_token = None
    gemini_api_key = os.environ.get("GEMINI_API_KEY") or ""
    
    # Try reading existing local configs to preserve details
    jira_conf_file = find_config("jira_config.json")
    if jira_conf_file:
        try:
            with open(jira_conf_file, "r") as f:
                data = json.load(f)
                project_key = data.get("project_key", project_key)
                jira_url = data.get("jira_url", jira_url)
                jira_email = data.get("jira_email", jira_email)
                jira_token = data.get("jira_token") or data.get("token")
        except Exception:
            pass
            
    discord_conf_file = find_config("discord_config.json")
    if discord_conf_file:
        try:
            with open(discord_conf_file, "r") as f:
                data = json.load(f)
                discord_channel_id = data.get("channel_id", discord_channel_id)
                discord_token = data.get("bot_token") or data.get("token")
        except Exception:
            pass

    # Try reading from global configurations
    global_jira = os.path.expanduser("~/.gemini/config/jira_config.json")
    if os.path.exists(global_jira):
        try:
            with open(global_jira, "r") as f:
                g_data = json.load(f)
                jira_url = jira_url or g_data.get("jira_url")
                jira_email = jira_email or g_data.get("jira_email")
                project_key = project_key or g_data.get("project_key")
                jira_token = jira_token or g_data.get("jira_token") or g_data.get("token")
        except Exception:
            pass

    global_discord = os.path.expanduser("~/.gemini/config/discord_config.json")
    if os.path.exists(global_discord):
        try:
            with open(global_discord, "r") as f:
                g_data = json.load(f)
                discord_channel_id = discord_channel_id or g_data.get("channel_id")
                discord_token = discord_token or g_data.get("bot_token") or g_data.get("token")
        except Exception:
            pass

    # Prompt interactive inputs if still missing
    if not jira_url:
        jira_url = input("[?] ระบุ JIRA URL (e.g. https://your-domain.atlassian.net): ").strip()
    if not jira_email:
        jira_email = input("[?] ระบุ JIRA Email: ").strip()
    if not project_key:
        project_key = input("[?] ระบุ JIRA Project Key: ").strip()
    if not discord_channel_id:
        discord_channel_id = input("[?] ระบุ Discord Channel ID: ").strip()

    # Always attempt to pull from 1Password CLI as biometric check
    print("[*] กำลังตรวจสอบความถูกต้องทางชีวภาพ (Touch ID / Passkey) ผ่าน 1Password...")
    # Target the correct reference format: op://Personal/Jira/credential
    JIRA_PASS_URIS = os.environ.get("JIRA_PASS_URIS", "").split(",") if os.environ.get("JIRA_PASS_URIS") else [
        "op://Personal/Jira/credential",
        "op://Private/Jira/credential",
        "op://Personal/Jira/password",
        "op://Private/Jira/password"
    ]
    
    op_success = False
    for uri in JIRA_PASS_URIS:
        try:
            print(f"[*] Trying to fetch: {uri} (Scan fingerprint if prompted)...")
            res = subprocess.run(["op", "read", uri], capture_output=True, text=True, check=True)
            fetched_token = res.stdout.strip()
            if fetched_token:
                jira_token = fetched_token
                op_success = True
                print(f"[+] ยืนยันตัวตนสำเร็จ! ปลดล็อคและดึง token จาก {uri} เรียบร้อย")
                break
        except subprocess.CalledProcessError:
            continue

    if not op_success:
        if jira_token:
            print("[!] ไม่สามารถติดต่อ 1Password CLI ได้, จะใช้ JIRA token เดิมจาก config ท้องถิ่น")
        else:
            print("[-] ล้มเหลว: ไม่สามารถตรวจผ่าน biometrics หรือหา token ใน 1Password ได้เลยครับบอส", file=sys.stderr)
            sys.exit(1)
            
    # Write to .env
    env_content = f"""# ⚠️ PRIVATE CREDENTIALS - GENERATED BY SETUP UTILITY
# DO NOT COMMIT THIS FILE TO GIT

GEMINI_API_KEY="{gemini_api_key}"
DISCORD_BOT_TOKEN="{discord_token}"
DISCORD_CHANNEL_ID="{discord_channel_id}"
JIRA_EMAIL="{jira_email}"
JIRA_TOKEN="{jira_token}"
JIRA_URL="{jira_url}"
JIRA_PROJECT_KEY="{project_key}"
"""
    
    env_path = os.path.join(os.getcwd(), ".env")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content.strip() + "\n")
    print("[+] สร้างไฟล์ .env เรียบร้อยที่:", env_path)
    
    # Check and update .gitignore
    gitignore_path = os.path.join(os.getcwd(), ".gitignore")
    ensure_gitignore = ".env"
    
    gitignore_content = ""
    if os.path.exists(gitignore_path):
        with open(gitignore_path, "r", encoding="utf-8") as f:
            gitignore_content = f.read()
            
    if ensure_gitignore not in gitignore_content.splitlines():
        with open(gitignore_path, "a", encoding="utf-8") as f:
            f.write(f"\n# Drunken AGY local credentials\n{ensure_gitignore}\n")
        print("[+] เพิ่ม .env ลงใน .gitignore เรียบร้อย (ปลอดภัยไม่ติด git)")
    else:
        print("[*] มี .env ใน .gitignore อยู่แล้ว")
        
    print("[+] การตั้งค่าเสร็จสิ้น! ทุกบริการของ agy จะอ่านตัวแปรจากไฟล์ .env โดยตรงโดยไม่ต้องสแกนนิ้วซ้ำแล้วครับบอส")

if __name__ == "__main__":
    main()

